apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gin-tattoo
  namespace: prod
  labels:
    app: gin-tattoo
    environment: prod
spec:
  selector:
    matchLabels:
      app: gin-tattoo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
