# kubectl create secret generic sonar-role-credentials --namespace database \
#   --from-literal=password=<SONAR_DB_PASSWORD> \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonar-role-credentials
  namespace: database
spec:
  encryptedData:
    password: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: sonar-role-credentials
      namespace: database
    type: Opaque
