# kubectl create secret generic jenkins-secrets --namespace jenkins \
#   --from-literal=github-token=<GH_TOKEN> \
#   --from-literal=sonar-token=<SONAR_TOKEN> \
#   --dry-run=client -o yaml | kubeseal --format yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-secrets
  namespace: jenkins
spec:
  encryptedData:
    github-token: REPLACE_WITH_KUBESEAL_OUTPUT
    sonar-token: REPLACE_WITH_KUBESEAL_OUTPUT
  template:
    metadata:
      name: jenkins-secrets
      namespace: jenkins
    type: Opaque
